config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions
  resources :characters
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :characters
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, :email, :alias, presence: true
  validates :email, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8}, presence: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def require_login
    unless session[:user_id]
      flash[:alert] = "You must be logged-in to access this page, doofus!"
      redirect_to '/'
    end
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:user_id, :name, :gender, :hit_points, :life, :speed, :initiative, :strength, :experience, :charisma, :intimidation, :weapon_proficiency, :weapon_accuracy, :tolerance)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    @user = User.new
  end

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    puts "user =", user
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(session[:user_id])
    else
      flash[:alert] = "Credentials incorrect or not found"
      redirect_to '/'
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
      if @user.save
        flash[:notice] = 'User Registered!'
        session[:user_id] = @user.id
        redirect_to user_path(session[:user_id])
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to '/'
      end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :alias)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= form_for(character) do |f| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" readonly>
    <%= f.label :user_id, "Owner: " %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :hit_points %>
    <button type="button" name="button">Roll</button>
    <%= f.number_field :hit_points %>
  </div>

  <div class="field">
    <%= f.label :life %>
    <%= f.number_field :life %>
  </div>

  <div class="field">
    <%= f.label :speed %>
    <%= f.number_field :speed %>
  </div>

  <div class="field">
    <%= f.label :initiative %>
    <%= f.number_field :initiative %>
  </div>

  <div class="field">
    <%= f.label :strength %>
    <%= f.number_field :strength %>
  </div>

  <div class="field">
    <%= f.label :experience %>
    <%= f.number_field :experience %>
  </div>

  <div class="field">
    <%= f.label :charisma %>
    <%= f.number_field :charisma %>
  </div>

  <div class="field">
    <%= f.label :intimidation %>
    <%= f.number_field :intimidation %>
  </div>

  <div class="field">
    <%= f.label :weapon_proficiency %>
    <%= f.number_field :weapon_proficiency %>
  </div>

  <div class="field">
    <%= f.label :weapon_accuracy %>
    <%= f.number_field :weapon_accuracy %>
  </div>

  <div class="field">
    <%= f.label :tolerance %>
    <%= f.number_field :tolerance %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Hit points</th>
      <th>Life</th>
      <th>Speed</th>
      <th>Initiative</th>
      <th>Strength</th>
      <th>Experience</th>
      <th>Charisma</th>
      <th>Intimidation</th>
      <th>Weapon proficiency</th>
      <th>Weapon accuracy</th>
      <th>Tolerance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.user %></td>
        <td><%= character.name %></td>
        <td><%= character.gender %></td>
        <td><%= character.hit_points %></td>
        <td><%= character.life %></td>
        <td><%= character.speed %></td>
        <td><%= character.initiative %></td>
        <td><%= character.strength %></td>
        <td><%= character.experience %></td>
        <td><%= character.charisma %></td>
        <td><%= character.intimidation %></td>
        <td><%= character.weapon_proficiency %></td>
        <td><%= character.weapon_accuracy %></td>
        <td><%= character.tolerance %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @character.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @character.gender %>
</p>

<p>
  <strong>Hit points:</strong>
  <%= @character.hit_points %>
</p>

<p>
  <strong>Life:</strong>
  <%= @character.life %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @character.speed %>
</p>

<p>
  <strong>Initiative:</strong>
  <%= @character.initiative %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @character.strength %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @character.experience %>
</p>

<p>
  <strong>Charisma:</strong>
  <%= @character.charisma %>
</p>

<p>
  <strong>Intimidation:</strong>
  <%= @character.intimidation %>
</p>

<p>
  <strong>Weapon proficiency:</strong>
  <%= @character.weapon_proficiency %>
</p>

<p>
  <strong>Weapon accuracy:</strong>
  <%= @character.weapon_accuracy %>
</p>

<p>
  <strong>Tolerance:</strong>
  <%= @character.tolerance %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RdsBeta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session[:user_id] %>
      <a href="/sessions/<%= session[:user_id] %>" class="btn btn-secondary" data-method="delete">Logout</a>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="container">
  <div class="form-control form-group">
    <%= form_for(user) do |f| %>
    <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-group">
      <%= f.label :first_name, :class => "control-label" %>
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, :class => "control-label"  %>
      <%= f.text_field :last_name, :class => "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :alias, :class => "control-label"  %>
      <%= f.text_field :alias, :class => "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :email, :class => "control-label"  %>
      <%= f.text_field :email, :class => "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :password, :class => "control-label"  %>
      <%= f.password_field :password, :class => "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, :class => "control-label"  %>
      <%= f.password_field :password_confirmation, :class => "form-control"  %>
    </div>

    <div class="form-actions">
      <%= f.submit "Update", :class => "btn btn-secondary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, :class => "btn btn-secondary" %> |
<%= link_to 'Back', users_path, :class => "btn btn-secondary" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>on users index - fix this, <%= current_user.alias %></h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Alias</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.alias %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, :class => "btn btn-secondary" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, :class => "btn btn-secondary" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="view-half">
  <div class="container">

    <div class="form-control form-group" readonly>
      <strong>First name:</strong>
      <div class="form-control form-group">
        <%= @user.first_name %>
      </div>

      <strong>Last name:</strong>
      <div class="form-control form-group">
        <%= @user.last_name %>
      </div>

      <strong>Alias:</strong>
      <div class="form-control form-group">
        <%= @user.alias %>
      </div>

      <strong>Email:</strong>
      <div class="form-control form-group">
        <%= @user.email %>
      </div>

      <div class="form-actions">
        <%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-secondary" %> |
        <%= link_to 'Back', users_path, :class => "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

<div class="view-half">
  <div class="container">
    Character(s) table here
    <%= link_to "New Character", new_character_url, :class => "btn btn-secondary" %>
  </div>
</div>